// This file is auto-generated from next.config.ts
// Do not edit this file directly.

export const WHITELISTED_IMAGE_DOMAINS = [
  'picsum.photos',
  'placehold.co',
  'm.media-amazon.com',
  'images-na.ssl-images-amazon.com',
];
